// <auto-generated />
using System;
using KwikNestaProperty.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KwikNestaProperty.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PropertyServiceDbContext))]
    [Migration("20260606232249_AddedUidToParticipantAndSettlementStatusToViewSessionTables")]
    partial class AddedUidToParticipantAndSettlementStatusToViewSessionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kn-property-svc")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.KNProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaSize")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("AreaUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParkingSpaces")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PriceFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Price")
                        .HasFilter("\"Status\" = 'Available'");

                    b.HasIndex("Type", "Price")
                        .HasFilter("\"Status\" = 'Available'");

                    b.HasIndex("Type", "Bedrooms", "Bathrooms")
                        .HasFilter("\"Status\" = 'Available'");

                    b.ToTable("Properties", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.OwnershipDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtherDocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("VerificationRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationRequestId");

                    b.ToTable("OwnershipDocuments", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.OwnershipVerificationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("OwnershipVerificationRequests", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PropertyFeatures", "kn-property-svc");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9bed23d9-8f16-4444-83d3-9a114a8e42f3"),
                            Category = "Interior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7500),
                            IsDeprecated = false,
                            Name = "Air Conditioning",
                            NameNormalized = "air conditioning"
                        },
                        new
                        {
                            Id = new Guid("8bed23d9-8f16-4444-83d3-9a114a8e42f4"),
                            Category = "Interior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7528),
                            IsDeprecated = false,
                            Name = "Furnished",
                            NameNormalized = "furnished"
                        },
                        new
                        {
                            Id = new Guid("7bed23d9-8f16-4444-83d3-9a114a8e42f5"),
                            Category = "Interior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7531),
                            IsDeprecated = false,
                            Name = "Semi-Furnished",
                            NameNormalized = "semi-furnished"
                        },
                        new
                        {
                            Id = new Guid("6bed23d9-8f16-4444-83d3-9a114a8e42f6"),
                            Category = "Interior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7533),
                            IsDeprecated = false,
                            Name = "Built-in Wardrobes",
                            NameNormalized = "built-in wardrobes"
                        },
                        new
                        {
                            Id = new Guid("5bed23d9-8f16-4444-83d3-9a114a8e42f7"),
                            Category = "Interior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7535),
                            IsDeprecated = false,
                            Name = "Smart Home System",
                            NameNormalized = "smart home system"
                        },
                        new
                        {
                            Id = new Guid("4bed23d9-8f16-4444-83d3-9a114a8e42f8"),
                            Category = "Interior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7536),
                            IsDeprecated = false,
                            Name = "Laundry Room",
                            NameNormalized = "laundry room"
                        },
                        new
                        {
                            Id = new Guid("3bed23d9-8f16-4444-83d3-9a114a8e42f9"),
                            Category = "Exterior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7548),
                            IsDeprecated = false,
                            Name = "Balcony",
                            NameNormalized = "balcony"
                        },
                        new
                        {
                            Id = new Guid("2bed23d9-8f16-4444-83d3-9a114a8e42f0"),
                            Category = "Exterior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7550),
                            IsDeprecated = false,
                            Name = "Terrace",
                            NameNormalized = "terrace"
                        },
                        new
                        {
                            Id = new Guid("1bed23d9-8f16-4444-83d3-9a114a8e42f1"),
                            Category = "Exterior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7553),
                            IsDeprecated = false,
                            Name = "Garden",
                            NameNormalized = "garden"
                        },
                        new
                        {
                            Id = new Guid("0bed23d9-8f16-4444-83d3-9a114a8e42f2"),
                            Category = "Exterior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7554),
                            IsDeprecated = false,
                            Name = "Fence",
                            NameNormalized = "fence"
                        },
                        new
                        {
                            Id = new Guid("abed23d9-8f16-4444-83d3-9a114a8e42fa"),
                            Category = "Exterior",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7556),
                            IsDeprecated = false,
                            Name = "Gated Compound",
                            NameNormalized = "gated compound"
                        },
                        new
                        {
                            Id = new Guid("bbed23d9-8f16-4444-83d3-9a114a8e42fb"),
                            Category = "Security",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7558),
                            IsDeprecated = false,
                            Name = "CCTV",
                            NameNormalized = "cctv"
                        },
                        new
                        {
                            Id = new Guid("cbed23d9-8f16-4444-83d3-9a114a8e42fb"),
                            Category = "Security",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7560),
                            IsDeprecated = false,
                            Name = "Security Doors",
                            NameNormalized = "security doors"
                        },
                        new
                        {
                            Id = new Guid("dbed23d9-8f16-4444-83d3-9a114a8e42fc"),
                            Category = "Security",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7562),
                            IsDeprecated = false,
                            Name = "Burglar Alarm",
                            NameNormalized = "burglar alarm"
                        },
                        new
                        {
                            Id = new Guid("ebed23d9-8f16-4444-83d3-9a114a8e42fd"),
                            Category = "Security",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7568),
                            IsDeprecated = false,
                            Name = "Gated Estate",
                            NameNormalized = "gated estate"
                        },
                        new
                        {
                            Id = new Guid("eced23d9-8f16-4444-83d3-9a114a8e42fe"),
                            Category = "Security",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7570),
                            IsDeprecated = false,
                            Name = "Security",
                            NameNormalized = "security"
                        },
                        new
                        {
                            Id = new Guid("eded23d9-8f16-4444-83d3-9a114a8e420e"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7571),
                            IsDeprecated = false,
                            Name = "Electricity",
                            NameNormalized = "electricity"
                        },
                        new
                        {
                            Id = new Guid("eeed23d9-8f16-4444-83d3-9a114a8e421e"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7573),
                            IsDeprecated = false,
                            Name = "Prepaid Meter",
                            NameNormalized = "prepaid meter"
                        },
                        new
                        {
                            Id = new Guid("e0ed23d9-8f16-4444-83d3-9a114a8e422e"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7578),
                            IsDeprecated = false,
                            Name = "Boys Quarters",
                            NameNormalized = "boys quarters"
                        },
                        new
                        {
                            Id = new Guid("e1ed23d9-8f16-4444-83d3-9a114a8e423e"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7580),
                            IsDeprecated = false,
                            Name = "Generator",
                            NameNormalized = "generator"
                        },
                        new
                        {
                            Id = new Guid("e2ed23d9-8f16-4444-83d3-9a114a8e424e"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7582),
                            IsDeprecated = false,
                            Name = "Inverter",
                            NameNormalized = "inverter"
                        },
                        new
                        {
                            Id = new Guid("e3ed23d9-8f16-4444-83d3-9a114a8e425e"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7583),
                            IsDeprecated = false,
                            Name = "Borehole",
                            NameNormalized = "borehole"
                        },
                        new
                        {
                            Id = new Guid("e4ed23d9-8f16-4444-83d3-9a114a8e426e"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7587),
                            IsDeprecated = false,
                            Name = "Water Suply",
                            NameNormalized = "water suply"
                        },
                        new
                        {
                            Id = new Guid("e5ed23d9-8f16-4444-83d3-9a114a8e427e"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7589),
                            IsDeprecated = false,
                            Name = "Cable TV",
                            NameNormalized = "cable tv"
                        },
                        new
                        {
                            Id = new Guid("e6ed23d9-8f16-4444-83d3-9a114a8e428e"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7590),
                            IsDeprecated = false,
                            Name = "Internet",
                            NameNormalized = "internet"
                        },
                        new
                        {
                            Id = new Guid("e7ed23d9-8f16-4444-83d3-9a114a8e429e"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7592),
                            IsDeprecated = false,
                            Name = "Parking Space",
                            NameNormalized = "parking space"
                        },
                        new
                        {
                            Id = new Guid("e8ed23d9-8f16-4444-83d3-9a114a8e4200"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7594),
                            IsDeprecated = false,
                            Name = "Swimming Pool",
                            NameNormalized = "swimming pool"
                        },
                        new
                        {
                            Id = new Guid("e9ed23d9-8f16-4444-83d3-9a114a8e4201"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7596),
                            IsDeprecated = false,
                            Name = "Gym",
                            NameNormalized = "gym"
                        },
                        new
                        {
                            Id = new Guid("00ed23d9-8f16-4444-83d3-9a114a8e4202"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7597),
                            IsDeprecated = false,
                            Name = "Jacuzzi",
                            NameNormalized = "jacuzzi"
                        },
                        new
                        {
                            Id = new Guid("01ed23d9-8f16-4444-83d3-9a114a8e4203"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7599),
                            IsDeprecated = false,
                            Name = "Garage",
                            NameNormalized = "garage"
                        },
                        new
                        {
                            Id = new Guid("02ed23d9-8f16-4444-83d3-9a114a8e4204"),
                            Category = "Utilities",
                            CreatedOn = new DateTime(2026, 6, 6, 23, 22, 49, 201, DateTimeKind.Utc).AddTicks(7603),
                            IsDeprecated = false,
                            Name = "Elevator",
                            NameNormalized = "elevator"
                        });
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyFeatureLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomFeature")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomFeatureNormalized")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomFeatureNormalized");

                    b.HasIndex("FeatureId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("PropertyId", "CustomFeatureNormalized")
                        .IsUnique()
                        .HasFilter("\"CustomFeatureNormalized\" IS NOT NULL");

                    b.HasIndex("PropertyId", "FeatureId")
                        .IsUnique()
                        .HasFilter("\"FeatureId\" IS NOT NULL");

                    b.ToTable("PropertyFeatureLinks", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyInquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OfferedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyInquiries", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_PropertyLocation_Lat_Lng_VerifiedOnly")
                        .HasFilter("\"VerificationStatus\" = 'Verified'");

                    b.ToTable("Locations", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyMedias", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NewPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyPriceHistories", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyViews", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.SessionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ViewingSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ViewingSessionId", "UId");

                    b.ToTable("SessionParticipants", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.ViewingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("ViewingRequests", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.ViewingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SetlementStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ViewingRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChannelName")
                        .IsUnique();

                    b.HasIndex("ViewingRequestId")
                        .IsUnique();

                    b.ToTable("ViewingSessions", "kn-property-svc");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.OwnershipDocument", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.OwnershipVerificationRequest", "VerificationRequest")
                        .WithMany("Documents")
                        .HasForeignKey("VerificationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerificationRequest");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.OwnershipVerificationRequest", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.KNProperty", "Property")
                        .WithMany("OwnershipVerificationRequests")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyFeatureLink", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.PropertyFeature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KwikNestaProperty.Domain.Entities.KNProperty", "Property")
                        .WithMany("FeatureLinks")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyInquiry", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.KNProperty", "Property")
                        .WithMany("Inquiries")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyLocation", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.KNProperty", "Property")
                        .WithOne("Location")
                        .HasForeignKey("KwikNestaProperty.Domain.Entities.PropertyLocation", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyMedia", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.KNProperty", "Property")
                        .WithMany("Media")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyPriceHistory", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.KNProperty", "Property")
                        .WithMany("PriceHistories")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.PropertyView", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.KNProperty", "Property")
                        .WithMany("PropertyViews")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.SessionParticipant", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.ViewingSession", "ViewingSession")
                        .WithMany("Participants")
                        .HasForeignKey("ViewingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ViewingSession");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.ViewingRequest", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.KNProperty", "Property")
                        .WithMany("ViewingRequests")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.ViewingSession", b =>
                {
                    b.HasOne("KwikNestaProperty.Domain.Entities.ViewingRequest", "ViewingRequest")
                        .WithOne("Session")
                        .HasForeignKey("KwikNestaProperty.Domain.Entities.ViewingSession", "ViewingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ViewingRequest");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.KNProperty", b =>
                {
                    b.Navigation("FeatureLinks");

                    b.Navigation("Inquiries");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("OwnershipVerificationRequests");

                    b.Navigation("PriceHistories");

                    b.Navigation("PropertyViews");

                    b.Navigation("ViewingRequests");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.OwnershipVerificationRequest", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.ViewingRequest", b =>
                {
                    b.Navigation("Session")
                        .IsRequired();
                });

            modelBuilder.Entity("KwikNestaProperty.Domain.Entities.ViewingSession", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
